name: Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Lint & Alembic
    steps:
      - uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
      - name: Install python dependencies with uv
        run: |
          uv sync
      - name: Run lint.sh
        run: |
          ./lint.sh --check
